# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
    Hi! I'm Alpar, sofware developer and architect,
    living in 
    <a href="https://en.wikipedia.org/wiki/Cluj-Napoca">Cluj-Napoca, Romania</a>
    and working remotely across the globe.<br />
    <br />
    <a href="https://ro.linkedin.com/in/torokalpar" class="fa fa-linkedin-square" aria-hidden="true"></a>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
