# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
    <div style="align:center;text-align:center" />
    <img src="/profile.jpg" class="img-circle" width="120" />
    <br />
    <br />
    <div style="font-size: 16pt; text-color: black;">
        <a class="fa fa-linkedin-square" href="https://ro.linkedin.com/in/torokalpar" aria-hidden="true"></a>
        <a class="fa fa-github-square fa-github-square" href="https://github.com/atorok/" aria-hidden="true"></a>
        <a class="fa fa-github-square fa-stack-overflow" href="https://stackoverflow.com/users/740641/alpar" aria-hidden="true"></a>
    </div>
    </div>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
